<?php defined('BASEPATH') or exit('No direct script access allowed'); ?>
<?php init_head(); ?>
<style>
    strong {
        font-weight: 600;
    }
</style>
<div id="wrapper">
    <div class="content">
        <div class="row">
            <div class="col-md-12">
                <div class="panel_s">
                    <div class="panel-body">
                        <?php echo form_open(admin_url('purchase/customer/' . $customer['userid']), array('id' => 'sale-agreement-form')); ?>
                        <input type="hidden" name="customer_id" value="<?php echo $customer['userid']; ?>">
                        <input type="hidden" name="sale_agreements" value="1">
                        <input type="hidden" name="agreement_master_id" value="<?php echo isset($master_id) ? $master_id : ''; ?>">
                        <!-- <input type="text" name="agreement_name" class="form-control " placeholder="Agreement Name" value="<?php echo isset($customer) ? $customer['agreement_name'] : ''; ?>"> -->
                        <br><br>
                        <p>AGREEMENT FOR SALE</p>
                        <p>(Without Possession)</p><br>
                        <?php $date_value = (isset($documentation) ? $documentation[0]['date'] : '') ?>
                        <?php $month_value = (isset($documentation) ? $documentation[0]['month'] : '') ?>
                        <?php $year_value = (isset($documentation) ? $documentation[0]['year'] : '') ?>
                        <p>THIS AGREEMENT FOR SALE is made and executed at Ahmedabad on this <input type="text" name="date" class="form-control input-sm" style="display:inline-block; width:auto;" placeholder="Date" value="<?php echo $date_value; ?>" /> day of <input type="text" name="month" class="form-control input-sm" style="display:inline-block; width:auto;" placeholder="Month" value="<?php echo $month_value; ?>" />, <input type="text" name="years" class="form-control input-sm" style="display:inline-block; width:auto;" placeholder="Year" value="<?php echo $year_value; ?>" />.</p><br>
                        <p>BETWEEN</p><br>
                        <p><i class="fa fa-arrow-right"></i> kautilya Developers PAN : AATFK 6344 G</p><br>
                        <p>A Partnership Firm, having its Registered office at : 16, Dena Bank Society, Near Kiran Park, Nava Vadaj, Ahmedabad - 380013 & having site office at, "Kautilya One-54", located at Opp. Swaminarayan Temple, B/h. Omkar Lotus, Chandkheda, Ahmedabad.</p><br>
                        <p>Hereinafter referred to as the “ Vendor ” and/or “ Developer ” (which expression shall, unless it be repugnant to the context or the meaning thereof, be deemed to mean and include its present and future partner, executors, administrators, legal representatives and permitted assigns etc.) of the FIRST PART;</p><br>
                        <p>AND</p><br>
                        <p>(1) <?= $customer['company']; ?></p>
                        <p>PAN No :- <?= $customer['pan_card'] ?><br>Aadhar No :- <?= $customer['adhar_card'] ?></p>

                        <p>Adult Residing at -<?= $customer['address'] ?></p><br>
                        <?php
                        if (!empty($customer2)) { ?>

                            <p>(2) <?= $customer2->company2; ?></p>
                            <p>PAN No :- <?= $customer2->pan_card_2 ?><br>Aadhar No :- <?= $customer2->adhar_card_2 ?></p>

                            <p>Adult Residing at -<?= $customer2->address_2 ?></p><br>
                        <?php }
                        ?>

                        <br>
                        <p>Hereinafter referred to as the “PURCHASER” (Which expression shall unless repugnant to the context and meaning thereof shall mean and include his / her / their / its heirs, legal representatives, executors, successors and assigns) of the SECOND PART.</p><br>
                        <p>The Vendor and Purchaser are hereinafter individually referred to as the ‘Party’ and collectively referred to as the ‘Parties’.</p><br>
                        <p>WHEREAS-</p><br>
                        <p>(A) The developer is seized and possessed of or otherwise well sufficiently entitled to all that piece and parcel of land bearing
                            1) Final Plot No. 321, admeasuring 3400 sq.mtrs. of Town Planning Scheme No. 76 / B (Chandkheda), allotted in lieu of Survey No. 875/3 admeasuring 5666 sq.mtrs. & 2) Final Plot No. 322, admeasuring 2125 sq.mtrs. of Town Planning Scheme No. 76 / B (Chandkheda), allotted in lieu of Survey No. 875/4 admeasuring 3541 sq.mtrs. situated within the village limits of Chandkheda, Taluka - Sabarmati in the Registration Sub - District of Ahmedabad - 2 (Vadaj) of District Ahmedabad (For the sake of convenience hereinafter referred to as the “Said Land”).</p><br>
                        <p>(B) The Non-Agricultural Permission for Residencial & Commercial purpose of the “Said Land” was granted by the Hon' District Collecter, Ahmedabad under 1) Order No. CB / NA / Ahmedabad / CHANDKHEDA / 875 / 3 / 1009284 / 2019 on 03-06-2019 for Survey No. 875 / 3 of Mouje Chandkheda and entry to that effect was mutated in the revenue record by mutation entry No. 13606 dated : 15-06-2019, which were certified by the competent authority on 29-07-2019 & 2) Order No. CB / LAND-1 / NA / SR - 956 / 2018 / FMPS NO - 323282 on 29-10-218 for Survey No. 875 / 4 of Mouje Chandkheda and entry to that effect was mutated in the revenue record by mutation entry No. 13372 dated :
                            15-12-2018, which were certified by the competent authority on 28-01-2019</p><br>
                        <p>(C) The Vendor has purchased the Said land Paiki 1) Survey No. 875 / 3 from Daksh enterprise, a partnership firm by sale deed registered in the office of the Sub-Registrar of Assurances of Ahmedabad - 2 (Vadaj) under Serial No. 5406, dated : 04-04-2022 and entry to that effect was mutated in the revenue record by mutation entry No. 14858, Dated : 12-04-2022, Which was certified by the competent authority on 13-05-2022 & 2) Survey No. 875 / 4 from Jayantibhai Prahladbhai Nayak, Dilipkumar alias Bipinkumar Prahladbhai Nayak, Rajendrakumar Prahladbhai Nayak, Kailasben D/o. Prahladbhai Nayak W/o. Kundanlal Nayak, Sudhaben D/o. Prahladbhai Nayak Wd/o. Maheshbhai Nayak, Nitinkumar Nandubhai Nayak, Bhavnaben D/o. Nandubhai Nayak W/o. Nileshbhai Nayak, Rinaben D/o. Nandubhai Nayak W/o. Jitendrakumar Sisodiya, Jyotiben D/o. Nandubhai Nayak W/o. Jayendrakumar Nayak, Ranjanben Wd/o. Nandubhai Prahladbhai Nayak, Ajaykumar Mahendrakumar Nayak, Amarkumar Mahendrakumar Nayak, Dipakkumar Mahendrakumar Nayak, Ashaben D/o. Mahendrakumar Nayak W/o. Krunalkumar Nayak & Pratimaben Wd/o. Mahendrakumar Prahladbhai Nayak by sale deed registered in the office of the Sub-Registrar of Assurances of Ahmedabad - 2 (Vadaj) under Serial No. 20546, dated : 22-11-2018. In said deed of sale Sankalp Infrastructure, a partnership firm remain there presence as confirming party and entry to that effect was mutated in the revenue record by mutation entry No. 13355, Dated : 01-12-2018, Which was certified by the competent authority on 03-01-2019.</p><br>
                        <?php $commencement_letter_no_value = (isset($documentation) ? $documentation[0]['commencement_letter_no'] : '') ?>
                        <p>(D) Ahmedabad Municipal Corporation granted permission for construction on said land by following Commencement Letter <input type="text" name="commencement_letter_no" class="form-control input-sm" style="display:inline-block; width:auto;" value="<?php echo $commencement_letter_no_value; ?>" /> issued on 28th July, 2022 and granted Development Permission.</p><br>
                        <p>Block No. Case No. (Rajachitthi No.)</p>
                        <p>A + B BHNTI / WZ / 210522 / CGDCRV / A6107 / R0 / M1</p>
                        <p>(Rajachitthi No. 06627 / 210522 / A6107 / R0 / M1)</p><br>
                        <p>C BHNTS / WZ / 210522 / CGDCRV / A6108 / R0 / M1</p>
                        <p>(Rajachitthi No. 06628 / 210522 / A6108 / R0 / M1)</p><br>
                        <p>D BHNTS / WZ / 210522 / CGDCRV / A6109 / R0 / M1</p>
                        <p>(Rajachitthi No. 06629 / 210522 / A6109 / R0 / M1)</p><br>
                        <p>(E) The “Said Developer” has floated scheme of Residential & Commercial units known as “ KAUTILYA ONE-54 ” (hereinafter referred to as the “Said Scheme”) on the “Said Land”.</p><br>
                        <p>(F) The said scheme has been registered under the Real Estate (Regulation and Development) Act, 2016 and under the rules of the Gujarat Real Estate (Regulation and Development) (General) Rules, 2017 under Rera Project Registration Referance No.
                            PR / GJ / Ahmedabad / ahmedabad CITY / AUDA / MAA10980 / 291122.</p><br>
                        <p>(G) The Vendor has initiated the construction as per the approved plan and Development permission.</p><br>
                        <?php $flat_no_value = (isset($documentation) ? $documentation[0]['flat_no'] : '') ?>
                        <?php $block_value = (isset($documentation) ? $documentation[0]['block'] : '') ?>
                        <?php $area_value = (isset($documentation) ? $documentation[0]['area'] : '') ?>
                        <?php $floor_no_value = (isset($documentation) ? $documentation[0]['floor_no'] : '') ?>
                        <?php $price_in_rupees_value = (isset($documentation) ? $documentation[0]['price_in_rupees'] : '') ?>
                        <?php $price_in_words_value = (isset($documentation) ? $documentation[0]['price_in_words'] : '') ?>
                        <?php
                        $block_name = get_block_name($customer['block_id']);
                        $flat_name = get_flat_name($customer['flat_id']);
                        $floor_name = get_floor_name($customer['floor_id']);
                        $banakhat_details = get_banakhat_details($customer['property_id'], $flat_name, $block_name, $floor_name);
                        ?>
                        <p>(H) The Party of the Second Part has visited the said scheme and has shown his / her / their / its willingness to purchase <strong> Flat No. <?php echo $flat_name; ?></strong> in <strong>Wing “<?php echo $block_name; ?>”</strong> having Carpet Area (“Carpet Area” means the net usable floor area of an Property, excluding the area covered by the external walls, areas under services shafts, exclusive balcony or verandah area and exclusive open terrace area but includes the area covered by the internal partition walls of the Property) admeasuring about 80.60 sq.mtrs. (i.e. <input type="text" name="area" class="form-control input-sm" style="display:inline-block; width:auto;" placeholder="Area in sq.mtrs" value="<?php echo $area_value; ?>" /> sq.mtrs. Built up area) situated on <strong><?= $floor_name ?></strong> of the said Scheme along with (i) Wash Area admeasuring 2.42 sq.mtrs.. (ii) Balcony admeasuring about 3.21 sq.mtrs.. in the scheme known as “ KAUTILYA ONE-54 ” together with undivided share in the said land admeasuring about 34.17 Sq.Mtrs. (for the sake of convenience hereinafter referred to as the “Said Property”) from the “Said Developer” at lump sum consideration amount of the said property is fixed for Rs. <?= $customer['final_amount']?>/- Rupees <?= convertToIndianCurrency($customer['final_amount']) ?> Only.</p><br>
                        <p>(I) The said entire consideration amount is included of the carpet area of the Unit, Wash Area & Balcony.</p><br>
                        <p>(J) The Vendor has provided the copies of Approved Lay-Out Plan, Key-Plan, Building Plan, Elevation Plan, Section Plan etc., N.A. permission, Sale Deed, 7/12 Extracts, all Mutation Entries No. 6, necessary orders/permissions, Loan Papers, Receipts of the Land Revenue, Title Clearance Certificate / Search Report etc. to the Party of the Second Part and after getting it verified through the Advocate / Solicitor / Legal Expert and after being satisfied with the same the Party of the Second Part has agreed to purchase the Said Property from the Vendor.</p><br>
                        <p>(K) The Vendor has given all the information about quality of the materials and goods used in the said scheme to the purchaser, which the Purchaser has got verified through their experts of the respective fields and the Purchaser is fully satisfied with same.</p><br>
                        <p>(L) The Vendor will obey all the terms and conditions, restriction laid down by the competent authority for passing the plan of the said scheme and will construct the said scheme accordingly. The vendor will be responsible for completing the construction of the said scheme and obtain B.U.Permission / Completion Certificate from the competent authority.</p><br>
                        <p>(M) The Parties herein hereby agrees to obey the following terms and conditions mentioned in this Agreement for Sale and also agrees to obey the Rules and Regulations / Laws enacted and framed from time to time by the Government.</p><br>
                        <p>NOW IT IS HEREBY AGREED BETWEEN THE PARTIES HERETO AS FOLLOWS :</p><br>
                        <p>(1) The “Said Developer” has agreed to sell to the party of the Second Part and the Party of the Second Part has agreed to purchase the “Said Property” (more particularly described in the schedule hereunder written) from the “Said Developer” at or for the entire negotiated lump sum consideration as mentioned hereinabove.</p><br>
                        <p>(2) The Party of the Second Part has paid the following amount of the entire negotiated lump sum consideration towards the Booking Amount / Earnest Money to the Said Developer as per the details mentioned below :</p><br><br><br><br>
                        <p>The Said Developer hereby acknowledges the receipt of the same and admits that the said amount shall be adjusted against the total consideration at the time of execution of Sale Deed.</p>
                        <p>The total consideration in respect of the Said Property shall be payable by the Party of the Second Part as per the payment schedule mentioned below :-</p><br>
                        <p>(i) Amount of 30% of the total consideration to be paid to the Vendor after the execution of Agreement.</p><br>
                        <p>(ii) Amount of 45% of the total consideration to be paid to the Vendor on completion of the Plinth of the building or wing in which the said Property is located.</p><br>
                        <p>(iii) Amount of 70% of the total consideration to be paid to the Vendor on completion of the slabs including podiums and stilts of the building or wing in which the said Property is located.</p><br>
                        <p>(iv) Amount of 75% of the total consideration to be paid to the Vendor on completion of the walls, internal plaster, floorings doors and windows of the said Property.</p><br>
                        <p>(v) Amount of 80% of the total consideration to be paid to the Vendor on completion of the Sanitary fittings, stair cases, lift wells, lobbies up to the floor level of the said Property.</p><br>
                        <p>(vi) Amount of 85% of the total consideration to be paid to the Vendor on completion of the external plumbing and external plaster, elevation, terraces with waterproofing of the building or wing in which the said Property is located.</p><br>
                        <p>(vii) Amount of 95% of the total consideration to be paid to the Vendor on completion of the lifts, water pumps, electrical fittings, electro, mechanical and environment requirements, entrance lobby/s, plinth protection, paving of areas appertain and all other requirements as may be prescribed in the Agreement of sale of the building or wing in which the said Property is located.</p><br>
                        <p>(viii) Balance Amount against and at the time of handing over of the possession of the Property to the Purchaser on or after receipt of B.U.Permission / completion certificate.</p><br>
                        <p>(3) The total consideration price as stated above excludes Taxes (consisting of tax paid or payable by the Vendor by way of Goods and Service Tax, and Cess or any other similar taxes which may be levied, in connection with the construction of and carrying out the project payable by the Vendor) up to the date of handing over the possession of the Said Property, which shall be separately / payable by the Purchaser in the manner as may be decided by the Vendor.</p><br>
                        <p>(4) The total consideration price is escalation-free, save and except escalations/increases, due to increase on account of development charges payable to the competent authority and/or any other increase in charges which may be levied or imposed by the competent authority Local Bodies / Government from time to time. The Vendor undertakes and agrees that while raising a demand on the Purchaser for increase in development charges, cost, or levies imposed by the competent authorities, etc., the Vendor shall enclose the said notification / order / rule / regulation published / issued in that behalf to that effect along with the demand letter being issued to the Purchaser, Which shall only be applicable on subsequent payments.</p><br>
                        <p>(5) REPRESENTATION AND WARRANTIES OF THE VENDOR:</p>
                        <p>(i) The Vendor has clear and marketable title with respect to the said land; as declared in the title report and has the requisite rights to carry out development upon the said land and also has actual, physical and legal possession of the said land for the implementation of the said scheme;</p><br>
                        <p>(ii) The Vendor has lawful rights and requisite approvals from the competent Authorities to carry out development of the said scheme and shall obtain requisite approvals from time to time to complete the development of the project;</p><br>
                        <p>(iii) There are no encumbrances upon the Project Land or the Project except those disclosed in the Title Report;</p><br>
                        <p>(iv) There are no litigations pending before any Court of law with respect to the said land or said scheme except those disclosed in the title report;</p><br>
                        <p>(v) All approvals, licenses and permits issued by the competent authorities with respect to the said scheme, said land and said building / wing are valid and subsisting and have been obtained by following due process of law. Further, all approvals, licenses and permits to be issued by the competent authorities with respect to the Project, project land and said building / wing shall be obtained by following due process of law and the Vendor has been and shall, at all times, remain to be in compliance with all applicable laws in relation to the Project, project land, Building / wing and common areas;</p><br>
                        <p>(vi) The Vendor has the right to enter into this Agreement and has not committed or omitted to perform any act or thing, whereby the right, title and interest of the Purchaser created herein, may prejudicially be affected;</p><br>
                        <p>(vii) The Vendor has not entered into any agreement for sale and/or development agreement or any other agreement/ arrangement with any person or party with respect to the said land, including the said scheme and the said property which will, in any manner, affect the rights of Purchaser under this Agreement;</p><br>
                        <p>(viii) The Vendor declares that the Vendor is not restricted in any manner whatsoever from selling the said property to the purchaser in the manner contemplated in this Agreement;</p><br>
                        <p>(6) The vendor will have to complete the construction of the said scheme as per the approved plan till 31-12-2026 and will have to obtain B.U.Permission / completion certificate.</p><br>
                        <p>(7) The Purchaser will not store in the said property any goods which are of hazardous, combustible or dangerous nature or are so heavy as to damage the construction or structure of the building in which the said property is situated or storing of which goods is objected to by the concerned local or other authority and shall take care while carrying heavy packages which may damage or likely to damage the staircases, common passages or any other structure of the building in which the said property is situated, including entrances of the building in which the said property is situated and in case any damage is caused to the building in which the Said Property is situated or the Said Property on account of negligence or default of the Purchaser in this behalf, the Purchaser shall be liable for the consequences of this breach.</p><br>
                        <p>(8) All and every cost, charges and expenses shall be borne and paid by the ALLOTTEE to the PROMOTER additionally. Such payment shall be made by the ALLOTTEE to the PROMOTER as and when demanded by the PROMOTER failing which, the ALLOTTEE shall be liable to pay interest at the rate SBI Marginal Cost of funds based Lending Rate (M.C.L.R.) + 2 % agreed hereunder for the delayed period on the outstanding amount till payment is made to the PROMOTER. Further, in any event, such outstanding amounts with interest thereon shall be paid by the ALLOTTEE to the PROMOTER before the execution and registration of the Deed of Conveyance by the PROMOTER in favour of the ALLOTTEE. At the same time PROMOTER fails to complete construction work and handingover possession within stipulated time period PROMOTER is liable to pay interest at the rate SBI Marginal Cost of funds based Lending Rate (MCLR) + 2 % to Allottee.</p><br>
                        <p>(9) Without prejudice to the right of Vendor to charge interest in terms of clause mentioned hereinabove, on the Purchaser committing default in payment on due date of any amount due and payable by the Purchaser to the Vendor under this Agreement (including his / her / their / its proportionate share of taxes levied by concerned local authority and other outgoings) and on the Purchaser committing three defaults of payment of installments, the Vendor shall at its own option, may terminate this Agreement. Provided that, Vendor shall give notice of fifteen days in writing to the Purchaser, by Registered Post AD at the address provided by the Purchaser or mail at the e-mail address provided by the Purchaser, or its intention to terminate this Agreement and of the specific breach or breaches of terms and conditions in respect of which it is intended to terminate the Agreement. If the Purchaser fails to rectify the breach or breaches mentioned by the Vendor within the period of notice then at the end of such notice period, Vendor shall be entitled to terminate this Agreement ex-parte.</p><br>
                        <p>(10) Provided further that upon termination of this Agreement as aforesaid, the Vendor shall refund to the Purchaser (subject to adjustment and recovery of any agreed liquidated damages or any other amount which may be payable to Vendor) within a period of thirty days of the termination, the installments of sale consideration of the said property which may till then have been paid by the Purchaser to the Vendor.</p><br>
                        <p>(11) The Vendor shall give possession of the property to the purchaser on or before 31-12-2026. If the Vendor fails or neglects to give possession of the Property to the Purchaser on account of reasons beyond the control the vendor and of its agents by the aforesaid date then the Vendor shall be liable on demand to refund to the Purchaser the amounts already received in respect of the Property with interest at the same rate as may be mentioned in the clause above herein above from the date the Vendor received the sum till the date the amounts and interest thereon is repaid.</p><br>
                        <p>Provided that the Vendor shall be entitled to reasonable extension of time for giving delivery of said property on the aforesaid date, if the completion of building in which the said property is to be situated is delayed on account of-</p>
                        <p>(i) War, civil commotion or act of God;</p>
                        <p>(ii) Any notice, order, rule, notification of the Government and/or other public or competent authority/court.</p><br>
                        <p>(12) The Vendor, upon obtaining the occupancy certificate from the competent authority and the payment made by the Purchaser as per the agreement shall offer in writing the possession of the said property, to the Purchaser in terms of this Agreement to be taken within 3 (three) months from the date of issue of such notice and the Vendor shall give possession of the said property to the Purchaser. The Vendor agrees and undertakes to indemnify the Purchaser in case of failure of fulfillment of any of the provisions, formalities, documentation on part of the Vendor. The Purchaser agree(s) to pay the maintenance charges as determined by the Vendor or association of Purchasers, as the case may be. The Vendor on its behalf shall offer the possession to the Purchaser in writing within 7 days of receiving the occupancy certificate of the Project.</p><br>
                        <p>The Purchaser shall take possession of the said property within 15 days of the written notice from the Vendor to the Purchaser intimating that the said property is ready for use and occupancy and if the purchaser fails to take the possession within 15 days of the written notice then the purchaser agrees to pay his / her / their / its proportionate maintenance expenses, security deposit in connection with the electricity, water connection in the said property and also to pay the escalation, if any .</p><br>
                        <p>(13) If within a period of five years from the date of handing over the Said Property to the Purchaser, the Purchaser brings to the notice of the Vendor any structural defect in the Said Property or the building in which the Said Property are situated or any defects on account of workmanship, quality or provision of service, then, whenever possible such defects shall be rectified by the Vendor at its own cost and in case it is not possible to rectify such defects, then the Purchaser shall be entitled to receive from the Vendor, compensation for such defect in the manner as provided under the Act.</p><br>
                        <p>Provided that the Vendor shall not be liable in respect of any structural defect or defects on account of workmanship, quality or provision of service which cannot be attributable to the Vendor or beyond the control of the Vendor.</p><br>
                        <p>(14) The Vendor shall confirm the final carpet area that has been allotted to the Purchaser after the construction of the Building is complete and the Building Use Permission / occupancy certificate is granted by the competent authority, by furnishing details of the changes, if any, in the carpet area, subject to a variation cap of three percent. The total price payable for the carpet area shall be recalculated upon condeveloperation by the Vendor. If there is any reduction in the carpet area within the defined limit then Vendor shall refund the excess money paid by Purchaser If there is any increase in the carpet area allotted to Purchaser, the Vendor shall demand additional amount from the Purchaser as per the next milestone of the Payment Plan. All these monetary adjustments shall be made at the same rate per square meter as agreed in above clause of this Agreement.</p><br>
                        <p>(15) The Vendor assures and declares unto the Purchaser that the said property was purchased out of the funds of Vendor and hence except the Vendor nobody else is having right, title, share, claim and interest and prior to the conveyance of the said Property, the Vendor has not sold, transferred, assigned, mortgaged or gifted the said property or any part thereof to anybody else and that there is no any order passed by any court of law restraining the Vendor from being sale, transfer, assign, mortgage of the said property to anybody else and that there are no legal proceedings standing or held on the said property by any court or authority nor any such order is issued or served by any court or authority and that the said property is not under any acquisition, requisition or reservation and that our titles to the said property are absolutely clear, marketable and saleable.</p><br>
                        <p>(16) The Promoter hereby declares that the Floor Space Index available as on date in respect of the project land is 6630 square meters only and Promoter has planned to utilize Floor Space Index of 14917.5 square meters by availing of TDR or FSI available on payment of premiums or FSI available as incentive FSI by implementing various scheme as mentioned in the Development Control Regulation or based on expectation of increased FSI which may be available in future on modification to Development Control Regulations, which are applicable to the said Project. The Promoter has disclosed the Floor Space Index of 14583.92 square meters as proposed to be utilized by him on the project land in the said Project and Allottee has agreed to purchase the said Apartment based on the proposed construction and sale of apartments to be carried out by the Promoter by utilizing the proposed FSI and on the understanding that the declared proposed FSI shall belong to Promoter only.</p><br>
                        <p>(17) In the event of sale not being completed due to any willful delay or default on the part of the Vendor, the Party of the Second Part shall have right to require specific performance by the Vendor of this agreement.</p><br>
                        <p>(18) The Purchaser will have to compulsorily become the member and obey the rules and regulations of the maintenance body to be formed in future. The purchaser will have to pay the amount of maintenance deposit, without any objection, to be collected by the maintenance body, in future.</p><br>
                        <p>(19) The Purchaser has clearly understood and agreed that the Unit-Holders of Unit No. A-101, A-102, A-103, A-104, B-101, B-102, B-103, B-104, C-101, C-102, C-103, C-104, D-101, D-102, D-103 & D-104 have got ingress and outgress to the terrace. None of the other Unit-holders of the said scheme have any right on this terrace. Another extra terrace will be common for all Unit-Holders. Unit-Holders of above mentioned unit nos. are not entitled to make any kind of temporary or permanent shade, structure or construction on said terrace. Further the purchaser has clearly understood and agreed that the unit holder of ground floor Flat No. A-001 & B-001 shall have exclusive use rights with respect to open back side margin space located adjoining to their wash yards. The Purchaser agrees and confirms the said condition and in future the Prospective Purchaser will not make any dispute or demand for the said permanent arrangement. The Unit-Holder shall allow the First Party / Maintenance Society to use the terrace for any utilities repairs and he / she / they is / are not entitled to raise any objection for the same.</p><br>
                        <p>(20) The purchaser cannot give the said property on lease, sub-lease, rent, leave and license or in any manner for his/her/their/its personal benefit till the total sale consideration of the said property is completed.</p><br>
                        <p>(21) The Purchaser cannot transfer the said property to anybody on the basis of this Agreement for Sale.</p><br>
                        <p>(22) The Purchaser/s are not entitled to make any change in interior/exterior elevation, exterior colour scheme of the said scheme. The Purchaser/s shall not be entitled to make any change/alteration in internal / external structure of the Said Property.</p><br>
                        <p>(23) The Purchaser/s is required to keep the ‘Said Property’, walls and partition walls, sewers, drains, pipes and appurtenances thereto belonging to, in good and tenantable repair and conditions and in particular so as to support, shelter and protect the parts of the building other than their property.</p><br>
                        <p>(24) The Purchaser shall have to maintain at their cost, the ‘Said Property’ in good condition, state and order, in which it is delivered to them and shall abide by all byelaws, rules and regulations of the government, electricity charges, local bodies and other authorities.</p><br>
                        <p>(25) The Purchaser shall have to pay / contribute proportionate amount to service society / association formed for the maintenance of said “ KAUTILYA ONE-54 ” Scheme.</p><br>
                        <p>(26) The Party of the Second Part will have access rights to all common amenities and common areas provided by the Party of the First Part. The Party of the Second Part will also not claim individual ownership rights in the undivided share in land.</p><br>
                        <p>(27) The Party of the Second Part shall have absolute right, interest, in the “Said Property” only after the date of final Sale Deed and after the possession of property, which shall be given at the time of execution of Sale Deed till such date the Party of Second Part shall not have any such claim or right to “Said Property”. he / she / they / it shall not claim any right, title, interest in any other common property of the Said Scheme.</p><br>
                        <p>(28) If any provision of this Agreement shall be determined to be void or unenforceable under the Act or the Rules and Regulations made there under or under other applicable laws, such provisions of the Agreement shall be deemed amended or deleted in so far as reasonably inconsistent with the purpose of this Agreement and to the extent necessary to conform to Act or the Rules and Regulations made there under or the applicable law, as the case may be, and the remaining provisions of this Agreement shall remain valid and enforceable as applicable at the time of execution of this Agreement.</p><br>
                        <p>(29) This Agreement for sale is to be read and understood as per the provisions made under the Real Estate (Regulation and Development) Act, 2016 and under the rules of the Gujarat Real Estate (Regulation and Development) (General) Rules, 2017.</p><br>
                        <p>(30) Any dispute between parties shall be settled amicably. In case of failure to settled the dispute amicably, which shall be referred to the RERA authority as per the provisions of the Real Estate (Regulation and Development) Act, 2016, Rules and Regulations, thereunder.</p><br>
                        <p>(31) That the rights and obligations of the parties under or arising out of this Agreement shall be construed and enforced in accordance with the laws of India for the time being in force and the Ahmedabad courts will have the jurisdiction for this Agreement.</p><br>
                        <p>(32) That all notices to be served on the Purchaser and the Vendor as contemplated by this Agreement shall be deemed to have been duly served if sent to the Purchaser or the Vendor by Registered Post A.D and notified Email ID/Under Certificate of Posting at their respective addresses specified below:</p>
                        <p>Details of Purchaser : as per this agreement.</p>
                        <p>Details of Vendor : as per this agreement.</p>
                        <p>It shall be the duty of the Purchaser and the Vendor to inform each other of any change in address subsequent to the execution of this Agreement in the above address by Registered Post failing which all communications and letters posted at the above address shall be deemed to have been received by the Vendor or the Purchaser, as the case may be.</p><br>
                        <p>(33) The out of pocket expenses, costs, and charges of and incidental to this agreement and the conveyance to be executed hereafter or for any writing declaration indemnity etc. such as stamp duty, registration fee, GST and all other taxes and also fees of Advocate / Solicitor for obtaining Title Clearance Certificate of the said property shall be borne by the party of the SECOND PART Only.</p><br>
                        <p>SCHEDULE ABOVE REFERRED TO</p>
                        <p>(Description of the said Immovable Vendor)</p>
                        <?php $flat_no2_value = (isset($documentation) ? $documentation[0]['flat_no2'] : '') ?>
                        <?php $block2_value = (isset($documentation) ? $documentation[0]['block2'] : '') ?>
                        <?php $floor2_value = (isset($documentation) ? $documentation[0]['floor2'] : '') ?>
                        <?php $area2_value = (isset($documentation) ? $documentation[0]['area2'] : '') ?>
                        <?php $area3_value = (isset($documentation) ? $documentation[0]['area3'] : '') ?>
                        <p>All That piece & parcel of Immovable property bearing <strong>Flat No. <?= $flat_name ?></strong> in <strong> Wing “<?= $block_name ?>”</strong> having total <strong>Carpet Area admeasuring about <?= $banakhat_details->carpet_area ?> sq.mtrs.</strong> situated on <strong><?= $floor_name ?></strong> of the said Scheme along with (i) <strong>Wash Area admeasuring <?= $banakhat_details->wash_yard ?> sq.mtrs</strong>. (ii) <strong>Balcony admeasuring about  <?= $banakhat_details->balcony ?> sq.mtrs</strong>.. in the scheme known as “ KAUTILYA ONE-54 ” together with <strong>undivided share in the said land admeasuring about  <?= round($banakhat_details->undivided_land_share, 2) ?> sq.mtrs</strong> bearing A) Final Plot No. 321, admeasuring 3400 sq.mtrs. of Town Planning Scheme No. 76 / B (Chandkheda), allotted in lieu of Survey No. 875/3 admeasuring 5666 sq.mtrs. & B) Final Plot No. 322, admeasuring 2125 sq.mtrs. of Town Planning Scheme No. 76 / B (Chandkheda), allotted in lieu of Survey No. 875/4 admeasuring 3541 sq.mtrs. situated within the village limits of Chandkheda, Taluka - Sabarmati in the Registration Sub - District of Ahmedabad - 2 (Vadaj) of District Ahmedabad.</p><br><br>
                        <p>DETAILS OF THE FOUR CORNERS OF THE SAID FLAT PROPERTY</p><br>
                        <p>East: <?= $banakhat_details->east ?></p>
                        <p>West : <?= $banakhat_details->west ?></p>
                        <p>North: <?= $banakhat_details->north ?></p>
                        <p>South: <?= $banakhat_details->south ?></p><br><br>
                        <p>IN WITNESS WHEREOF the “Said Developer” hereto through its authorized Partner has hereunto executed this Agreement on the Day Month and year herein above written.</p><br>
                        <p>SIGNED AND DELIVERED BY THE</p>
                        <p>PARTY OF THE FIRST PART :-</p><br>
                        <p><i class="fa fa-arrow-right"></i> kautilya Developers</p>
                        <p>A Partnership Firm</p>
                        <p>through its authorise signatory</p>
                        <p>Kiran Rasiklal Kamdar</p><br>
                        <br><br>
                        <p>In the presence of following</p>
                        <p>two Witness :-</p><br>
                        <br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
                        <p>SCHEDULE</p>
                        <p>AS PER SECTION 32(A) OF THE REGISTRATION ACT</p><br>
                        <p>Signature, Photograph and Thumb Impression of First Part:-</p><br><br><br><br><br><br><br>
                        <br>
                        <p><i class="fa fa-arrow-right"></i> kautilya Developers - A Partnership Firm through its authorise signatory Kiran Rasiklal Kamdar</p><br>
                        <p>Signature, Photograph and Thumb Impression of Second Part:-</p><br><br><br><br><br><br>
                        <br><br><br><br><br>
                        <br>
                        <div class="btn-bottom-toolbar btn-toolbar-container-out text-right">
                            <button class="btn btn-info only-save customer-form-submiter">
                                <?php echo _l('submit'); ?>
                            </button>

                        </div>
                        <?php echo form_close(); ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<?php init_tail(); ?>
</body>

</html>